# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TGTestKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TGTestKit
#   pod 'libextobjc', '~> 0.4.1'
	pod 'AFNetworking', '3.1.0'
end
