# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TGCacheDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inhibit_all_warnings!

  # Pods for TGCacheDemo
  pod 'SDWebImage', '~> 4.2.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'FMDB', '~> 2.6.2'
  pod 'GYDataCenter', '~> 0.1.1'
  pod 'YYCache', '~> 1.0.4'
#  pod 'YTKNetwork', '~> 2.0.4'
end
