# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TGRacDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inhibit_all_warnings!
  pod 'ReactiveCocoa', '~> 2.5'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'objectiveflickr', '2.0.4'
  pod 'LinqToObjectiveC', '2.0.0'
  pod 'SDWebImage', '3.7.1'
  # Pods for TGRacDemo

end
