# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TGRacDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ReactiveCocoa', '~> 2.5'
  pod 'SVProgressHUD', '~> 2.1.2'
  # Pods for TGRacDemo

end
